annotations:
  nginx.ingress.kubernetes.io/service-upstream: "true"
class: nginx
host: ${resources.dns.outputs.host}
routePaths: ${resources.dns<route.outputs.path}
routePorts: ${resources.dns<route.outputs.port}
routeServices: ${resources.dns<route.outputs.service}
templates:
  init: |-
    tls_secret_name: {{ if
      (or
        .driver.values.no_tls
        (and
          (hasKey .driver.values "tls_secret_name" )
          (ne .driver.values.tls_secret_name "" )
        )
      ) -}}
      ""
    {{- else -}}
      ${resources.tls-cert.outputs.tls_secret_name}
    {{- end }}
  manifests: |-
    {{- if gt (len .driver.values.routePaths ) 0 -}}
    ingress.yaml:
      location: namespace
      data:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          {{- if hasKey .driver.values "annotations" }}
          annotations: {{ .driver.values.annotations | toRawJson }}
          {{- end}}
          {{- if hasKey .driver.values "labels" }}
          labels: {{ .driver.values.labels | toRawJson }}
          {{- end}}
          name: {{ .id }}-ingress
        spec:
          {{- if .driver.values.class }}
          ingressClassName: {{ .driver.values.class | toRawJson }}
          {{- end }}
          rules:
          - host: {{ .driver.values.host | toRawJson }}
            http:
              paths:
              {{- /*
                We are guaranteed that .driver.values.routePaths is non-zero in
                length from the top level if statement, so we don't need
                to deal with the empty condition.
              */ -}}
              {{- range $index, $path := .driver.values.routePaths }}
              - path: {{ $path | toRawJson }}
                pathType: {{ $.driver.values.path_type | default "Prefix" | toRawJson }}
                backend:
                  service:
                    name: {{ index $.driver.values.routeServices $index  | toRawJson }}
                    port:
                      number: {{ index $.driver.values.routePorts $index }}
              {{- end }}
          {{- if not (or .driver.values.no_tls (eq .init.tls_secret_name "")) }}
          tls:
          - hosts:
            - {{ .driver.values.host | toRawJson }}
            secretName: {{ .init.tls_secret_name | quote }}
          {{- end }}
    {{- end -}}
  outputs: |-
    no_tls: {{ .driver.values.no_tls | default false }}
    id: {{ .id }}-ingress
    tls_secret_name: {{ .init.tls_secret_name }}