apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: test
entity:
  name: test
  type: ingress
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |-
          host: ${resources.dns.outputs.host}
          routePaths: ${resources.dns<route.outputs.path}
          routePorts: ${resources.dns<route.outputs.port}
          routeServices: ${resources.dns<route.outputs.service}
        manifests: |-
          {{- if gt (len .init.routePaths ) 0 -}}
          ingress.yaml:
            location: namespace
            data:
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                {{- if hasKey .driver.values "annotations" }}
                annotations: {{ .driver.values.annotations | toRawJson }}
                {{- end}}
                {{- if hasKey .driver.values "labels" }}
                labels: {{ .driver.values.labels | toRawJson }}
                {{- end}}
                name: {{ .id }}-ingress
              spec:
                {{- if .driver.values.class }}
                ingressClassName: {{ .driver.values.class | toRawJson }}
                {{- end }}
                rules:
                - host: {{ .init.host | toRawJson }}
                  http:
                    paths:
                    {{- /*
                      We are guaranteed that .init.routePaths is non-zero in
                      length from the top level if statement, so we don't need
                      to deal with the empty condition.
                    */ -}}
                    {{- range $index, $path := .init.routePaths }}
                    - path: {{ $path | toRawJson }}
                      pathType: {{ $.driver.values.path_type | default "Prefix" | toRawJson }}
                      backend:
                        service:
                          name: {{ index $.init.routeServices $index  | toRawJson }}
                          port:
                            number: {{ index $.init.routePorts $index }}
                    {{- end }}
                {{- if not (or .driver.values.no_tls (eq (.driver.values.tls_secret_name | default "") "")) }}
                tls:
                - hosts:
                  - {{ .init.host | toRawJson }}
                  secretName: {{ .driver.values.tls_secret_name | toRawJson }}
                {{- end }}
          {{- end -}}
        outputs: |-
          no_tls: {{ .driver.values.no_tls | default false }}
          id: {{ .id }}-ingress
